server:
  port: 9091
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:registrationdb
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  sql:
    init:
      platform: h2
      
phonebook:
     messages:
         saveSucc: contact saved successfully
         updateSucc: contact updated successfully
         saveFail: Failed to save the contact